update

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -11,6 +11,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Verify Secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "Error: DOCKER_USERNAME is missing"; exit 1; fi
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "Error: DOCKER_PASSWORD is missing"; exit 1; fi
+          echo "All necessary secrets are present."
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
